[package]
name = "tudelft-quadrupel"
version = "0.1.0"
edition = "2021"
authors = ["Jonathan Dönszelmann <jonabent@gmail.com>", "Victor Roest <victor@xirion.net>"]
license = "MIT"
description = "Hardware support library for the quadrupel drone project (embedded systems lab)."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
